name: AniLib translation artifact
on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test Custom
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            description: Automated AniLib translation notification.
            details: Generated Translation Test App. Visit the link to download and view the translation.
            footer: This is a footer.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}